#!/bin/sh
# Node REPL with Sagebrush loaded: `sagebrush`, and `m` = sagebrush.modsym.
cd "$(dirname "$0")"
exec node -i -e 'globalThis.sagebrush = require("./node"); globalThis.m = sagebrush.modsym; console.log("sagebrush loaded; m = sagebrush.modsym:", Object.keys(m).join(", "))'
