//! Galois orbits of newforms at prime level N <= 300 against Sage: the
//! dimension of every orbit and tr(T_p | A) for primes p <= 200, p != N
//! (fixtures/sage_prime_orbits_le300.jsonl, generated by
//! `sage fixtures/make_sage_prime_orbits.sage 11 300 OUT`).  Factoring
//! uses FLINT through sagebrush-flint (a dev-dependency only).

use std::collections::HashMap;

#[test]
fn prime_level_orbits_match_sage_up_to_300() {
    let mut sage: HashMap<u64, Vec<(usize, Vec<(u64, i64)>)>> = HashMap::new();
    for line in include_str!("fixtures/sage_prime_orbits_le300.jsonl").lines() {
        let v: serde_json::Value = serde_json::from_str(line).unwrap();
        let mut tr: Vec<(u64, i64)> = v["traces"].as_object().unwrap().iter().map(|(p, t)| (p.parse().unwrap(), t.as_i64().unwrap())).collect();
        tr.sort();
        sage.entry(v["level"].as_u64().unwrap()).or_default().push((v["dim"].as_u64().unwrap() as usize, tr));
    }
    let factor = |f: &[num_bigint::BigInt]| sagebrush_flint::factor(f).1;
    let mut count = 0;
    for (&n, theirs) in sage.iter_mut() {
        let orbits = sagebrush_modsym::orbits::prime_level_orbits(n, 200, &factor).unwrap();
        let mut ours: Vec<(usize, Vec<(u64, i64)>)> = orbits.into_iter().map(|o| (o.dim, o.traces)).collect();
        ours.sort();
        theirs.sort();
        assert_eq!(&ours, theirs, "N={}", n);
        count += ours.len();
    }
    assert_eq!(count, include_str!("fixtures/sage_prime_orbits_le300.jsonl").lines().count());
}
