//! a_p against Sage for 11 curves (rank 0-3, torsion up to Z/4 x Z/2, CM
//! with j = 0 and j = 1728, large coefficients) at every prime below 20000,
//! including which primes are bad: fixtures/sage_aplists.txt, regenerated by
//! `sage fixtures/make_sage_aplists.sage`.

use sagebrush_ap::{aplist, EllipticCurve};

#[test]
fn ap_matches_sage_below_20000() {
    let mut curves = 0;
    for line in include_str!("fixtures/sage_aplists.txt").lines() {
        let w: Vec<&str> = line.split(' ').collect();
        let a: Vec<i64> = w[1].split(',').map(|s| s.parse().unwrap()).collect();
        let e = EllipticCurve::new([a[0], a[1], a[2], a[3], a[4]]).unwrap();
        let bad: Vec<u64> = if w[2] == "-" { vec![] } else { w[2].split(',').map(|s| s.parse().unwrap()).collect() };
        let mut expected = std::collections::HashMap::new();
        for pa in &w[3..] {
            let (p, ap) = pa.split_once(':').unwrap();
            expected.insert(p.parse::<u64>().unwrap(), ap.parse::<i64>().unwrap());
        }
        for (p, ap) in aplist(&e, 19999) {
            if bad.contains(&p) {
                assert_eq!(ap, None, "{} p={}", w[0], p);
            } else {
                assert_eq!(ap, Some(expected[&p]), "{} p={}", w[0], p);
            }
        }
        curves += 1;
    }
    assert_eq!(curves, 11);
}
